CREATE TABLE `tasks` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`title` VARCHAR(255) NOT NULL,
	`description` VARCHAR(255) NOT NULL,
	`createBy` VARCHAR(255) NOT NULL,
	`status` VARCHAR(255) DEFAULT NULL,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);